-- Gives every request an opaque public identifier.
--
-- WHY THIS IS A SECOND COLUMN AND NOT A NEW PRIMARY KEY. `requests.id` is not
-- merely an identifier, it is ADR-10's FIFO ORDERING KEY -- `queueHeads` runs
-- `SELECT MIN(q.id)`, and 0001 chose a monotonic integer specifically because it
-- is "safer than a timestamp, which can tie". Replacing it with any UUID would
-- put ordering at the mercy of that UUID's resolution, and in SQLite it would
-- also cost the rowid: `INTEGER PRIMARY KEY` IS the rowid, so a text key adds an
-- index and turns every queue lookup into a seek plus a fetch.
--
-- So the two jobs are split. `id` orders. `public_id` identifies, and is the
-- only one that appears in a URL or an API response.
--
-- WHY v4 AND NOT v7. The entire purpose of this column is to be unguessable, and
-- a UUIDv7 spends its first 48 bits on a plaintext millisecond timestamp,
-- leaving 74 random. v4 has 122. **A v7 value also republishes its own creation
-- time to anyone holding it**, which is precisely the kind of incidental meaning
-- this column exists to strip out. v7 is the better default for a primary key,
-- where time-ordering buys index locality -- that is not this column's job.
--
-- Generated by `crypto.randomUUID()` in the Worker, which the runtime provides
-- with a cryptographically secure RNG. ADR-14's second test, "is the platform
-- already doing it?", answers yes, so no dependency is needed.

CREATE TABLE requests_rebuilt (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,

  -- Opaque, unguessable, and the ONLY request identifier that leaves the server.
  -- NOT NULL and UNIQUE are both load-bearing: a null would silently become an
  -- unaddressable request, and a duplicate would let one user's withdraw reach
  -- another's row before the nsid check ever ran.
  public_id       TEXT    NOT NULL UNIQUE,

  nsid            TEXT    NOT NULL REFERENCES users (nsid) ON DELETE CASCADE,
  photo_id        TEXT    NOT NULL,
  group_id        TEXT    NOT NULL,

  state           TEXT    NOT NULL DEFAULT 'pending'
                          CHECK (state IN ('pending', 'resolved')),

  outcome         TEXT    CHECK (outcome IN (
                            'succeeded',
                            'already_in_pool',
                            'queued_for_moderator',
                            'failed',
                            'withdrawn'
                          )),

  flickr_code     INTEGER,

  attempts        INTEGER NOT NULL DEFAULT 0,
  created_at      INTEGER NOT NULL,
  last_attempt_at INTEGER,
  resolved_at     INTEGER,

  CHECK (
    (state = 'pending'  AND outcome IS NULL     AND resolved_at IS NULL) OR
    (state = 'resolved' AND outcome IS NOT NULL AND resolved_at IS NOT NULL)
  )
) STRICT;

-- Existing rows get a real v4 built from SQLite's own CSPRNG. The layout is
-- 8-4-4-4-12 hex with the version nibble pinned to 4 and the variant nibble to
-- one of 8/9/a/b, so these are indistinguishable from the ones the Worker mints.
INSERT INTO requests_rebuilt
  (id, public_id, nsid, photo_id, group_id, state, outcome, flickr_code,
   attempts, created_at, last_attempt_at, resolved_at)
SELECT
   id,
   lower(
     hex(randomblob(4)) || '-' ||
     hex(randomblob(2)) || '-4' ||
     substr(hex(randomblob(2)), 2) || '-' ||
     substr('89ab', 1 + (abs(random()) % 4), 1) ||
     substr(hex(randomblob(2)), 2) || '-' ||
     hex(randomblob(6))
   ),
   nsid, photo_id, group_id, state, outcome, flickr_code,
   attempts, created_at, last_attempt_at, resolved_at
FROM requests;

DROP TABLE requests;

ALTER TABLE requests_rebuilt RENAME TO requests;

CREATE INDEX idx_requests_queue
  ON requests (nsid, group_id, id)
  WHERE state = 'pending';

CREATE INDEX idx_requests_pair
  ON requests (nsid, photo_id, group_id);

CREATE UNIQUE INDEX idx_requests_one_pending_per_pair
  ON requests (nsid, photo_id, group_id)
  WHERE state = 'pending';
