#!/usr/bin/env python3
"""Refuse a live count of tests, mutations or checks stated in prose.

A number in a document has nothing keeping it true. This project has now corrected the
same number six times -- four recorded inside `CLAUDE.md` itself, plus `CLAUDE.md` saying
305 and `README.md` saying 297 on the day the runner printed 303. **Every one of those
corrections was made by running the gate. Not one was caught by reading.**

So this check does not verify the number. It forbids it. An absent number cannot rot.

Two checks run here, and they work in opposite directions on purpose:

1. **FORBID** a live count in tracked markdown. A historical sentence carries
   `STALE-COUNT-EXEMPT: <reason>` on the line, the same shape `DIRTY-WORDS-EXEMPT` uses.
2. **VERIFY** the gate's step count in `CLAUDE.md` against `package.json`. That one is
   derivable, so forbidding it would throw away a fact the repository can prove.

Both polarities self-test on every run. A checker validated in one direction is
half-validated -- prove it stays silent on good input as well as loud on bad.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT: Path = Path(__file__).resolve().parent.parent

MARKER: str = "STALE-COUNT-EXEMPT"

# Generated or frozen files. Each one names why, because a bare skip list is a list
# nobody can re-litigate.
SKIP: dict[str, str] = {
    "docs/TRACEABILITY.md": "Generated by scripts/traceability.py, which checks its own staleness",
    "docs/WORK-LOG.md": "Frozen. Kept for its history, superseded by the board",
}

# The units that have actually drifted here. The list stays explicit rather than becoming
# a pattern over every noun, for the reason scripts/claude-dirty-words.py states: a
# checker that cries wolf gets switched off within a day.
#
# **PLURAL ONLY, and that is not tidiness.** The singular arm matched `RFC 2202 test
# vectors` in docs/FLICKR.md on this script's first run -- a standards number read as a
# count. A live claim of one test is not a thing anybody writes, so the singular arm cost
# a false positive and bought nothing.
COUNT: re.Pattern[str] = re.compile(
    r"\b\d{1,4}\s+(?:test blocks|tests|mutations|checks|decisions)\b",
    re.IGNORECASE,
)

STEPS: re.Pattern[str] = re.compile(r"\*\*([A-Za-z]+|\d+) steps, in this order\.\*\*")

NUMBER_WORDS: dict[str, int] = {
    word: value
    for value, word in enumerate(
        [
            "zero",
            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "ten",
            "eleven",
            "twelve",
            "thirteen",
            "fourteen",
            "fifteen",
            "sixteen",
            "seventeen",
            "eighteen",
            "nineteen",
            "twenty",
        ]
    )
}


def hits_in(text: str) -> list[tuple[int, str, str]]:
    """Return every forbidden count in `text` as (line number, matched text, line)."""
    found: list[tuple[int, str, str]] = []
    for number, line in enumerate(text.splitlines(), start=1):
        if MARKER in line:
            continue
        found.extend(
            (number, match.group(0), line.strip()) for match in COUNT.finditer(line)
        )
    return found


def tracked_markdown() -> list[str]:
    """Return every git-tracked markdown path, repository-relative, with / separators."""
    result = subprocess.run(
        ["git", "ls-files", "*.md"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def gate_steps() -> int:
    """Return how many steps `npm run check` runs, read from package.json."""
    raw = (REPO_ROOT / "package.json").read_text(encoding="utf-8")
    check: str = json.loads(raw)["scripts"]["check"]
    return len([step for step in check.split("&&") if step.strip()])


def documented_steps(text: str) -> tuple[int, int] | None:
    """Return (line number, count) for the gate's step count in `text`, or None."""
    for number, line in enumerate(text.splitlines(), start=1):
        match = STEPS.search(line)
        if match is None:
            continue
        token = match.group(1).lower()
        if token.isdigit():
            return (number, int(token))
        if token in NUMBER_WORDS:
            return (number, NUMBER_WORDS[token])
        return (number, -1)
    return None


def self_test() -> bool:
    """Prove both polarities. Returns True when every case behaves."""
    must_fire: list[str] = [
        "The gate runs 305 tests, the traceability gate, and the web build.",
        "It breaks the source in 46 mutations and checks the suite screams.",
        "Deleting the first pass left all 53 checks green.",
        "The matrix holds 61 test blocks today.",
        "There are 25 decisions in this file.",
        "It passed 24 Tests on the first run.",
    ]
    must_not_fire: list[str] = [
        # This one is the defect the first run found. Keep it first.
        "**`workerd` implements HMAC-SHA1.** Verified against RFC 2202 test vectors.",
        f"Nothing failed and 297 tests passed throughout.   <!-- {MARKER}: historical -->",
        "Quote the number the runner prints, never one read from a document.",
        "The ADR-23 Rule 3 import gate reads two committed indexes.",
        "The second mutation, on the surviving filter, drew 5 failures.",
        "**Sixteen steps, in this order.** Typecheck, Biome, the dirty-words check.",
        "This count has now been wrong FOUR times.",
        "The suite is green.",
        "Read `scripts/lrc-sdk-api.json`, 355 members across 38 namespaces.",
    ]

    failures: list[str] = [f"MISSED: {case}" for case in must_fire if not hits_in(case)]
    for case in must_not_fire:
        found = hits_in(case)
        if found:
            failures.append(f"FALSE POSITIVE on {case!r}: matched {found[0][1]!r}")

    if failures:
        print("Self-test FAILED:")
        for failure in failures:
            print(f"  {failure}")
        return False

    print(
        f"Self-test passed: {len(must_fire)} lines fire, {len(must_not_fire)} stay silent."
    )
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refuse a live count of tests, mutations or checks stated in prose."
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="run only the self-test and exit",
    )
    args = parser.parse_args()

    if not self_test():
        return 1
    if args.self_test:
        return 0

    problems: int = 0
    scanned: int = 0

    for relative in tracked_markdown():
        if relative in SKIP:
            print(f"Skipped {relative} -- {SKIP[relative]}.")
            continue
        path = REPO_ROOT / relative
        text = path.read_text(encoding="utf-8")
        scanned += 1
        for number, matched, line in hits_in(text):
            problems += 1
            print(f"{relative}:{number}: states a live count -- {matched!r}")
            print(f"    {line}")

    expected = gate_steps()
    claude_md = (REPO_ROOT / "CLAUDE.md").read_text(encoding="utf-8")
    documented = documented_steps(claude_md)
    if documented is None:
        problems += 1
        print("CLAUDE.md: no gate step count found. Expected '**N steps, in this order.**'.")
    else:
        line_number, stated = documented
        if stated != expected:
            problems += 1
            print(
                f"CLAUDE.md:{line_number}: says {stated} gate steps, "
                f"package.json runs {expected}."
            )
        else:
            print(f"Gate step count agrees: {expected} steps in package.json and CLAUDE.md.")

    if problems:
        print()
        print(f"Found {problems} stale-count problem(s).")
        print(
            f"A live count belongs in the runner's output, not in prose. "
            f"Mark a historical sentence with '{MARKER}: <reason>' on its line."
        )
        return 1

    print(f"No live counts in prose. Scanned {scanned} tracked markdown files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
