#!/usr/bin/env python3
"""Refuse a live count of tests, mutations or checks stated in prose.

A number in a document has nothing keeping it true. This project has now corrected the
same number six times -- four recorded inside `CLAUDE.md` itself, plus `CLAUDE.md` saying
305 and `README.md` saying 297 on the day the runner printed 303. **Every one of those
corrections was made by running the gate. Not one was caught by reading.**

So this check does not verify the number. It forbids it. An absent number cannot rot.

Four checks run here, and the split between them is the whole design: **forbid what
nothing can derive, verify what something can.**

1. **FORBID** a live count in tracked markdown. A historical sentence carries
   `STALE-COUNT-EXEMPT: <reason>` on the line, the same shape `DIRTY-WORDS-EXEMPT` uses.
2. **VERIFY** the gate's step count in `CLAUDE.md` against `package.json`.
3. **VERIFY** the language table's file counts against `git ls-files`. It said 50, 14 and
   16 against a real 56, 15 and 22, and the Lua figure had been wrong for a day.
4. **VERIFY** every route path the documents name against the routes `src/` declares. The
   README named a deleted device-link prefix for a day, in the row describing the
   protected surface.

**Deleting a derivable number would throw away a fact the repository can prove**, which
is why only the first is a prohibition.

Both polarities self-test on every run. A checker validated in one direction is
half-validated -- prove it stays silent on good input as well as loud on bad.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO_ROOT: Path = Path(__file__).resolve().parent.parent

MARKER: str = "STALE-COUNT-EXEMPT"

# Generated or frozen files. Each one names why, because a bare skip list is a list
# nobody can re-litigate.
SKIP: dict[str, str] = {
    "docs/TRACEABILITY.md": "Generated by scripts/traceability.py, which checks its own staleness",
    "docs/WORK-LOG.md": "Frozen. Kept for its history, superseded by the board",
}

# The units that have actually drifted here. The list stays explicit rather than becoming
# a pattern over every noun, for the reason scripts/claude-dirty-words.py states: a
# checker that cries wolf gets switched off within a day.
#
# **PLURAL ONLY, and that is not tidiness.** The singular arm matched `RFC 2202 test
# vectors` in docs/FLICKR.md on this script's first run -- a standards number read as a
# count. A live claim of one test is not a thing anybody writes, so the singular arm cost
# a false positive and bought nothing.
COUNT: re.Pattern[str] = re.compile(
    r"\b\d{1,4}\s+(?:test blocks|tests|mutations|checks|decisions)\b",
    re.IGNORECASE,
)

STEPS: re.Pattern[str] = re.compile(r"\*\*([A-Za-z]+|\d+) steps, in this order\.\*\*")

# **CLAUDE.md's language-tooling table, which is DERIVABLE and therefore verified rather
# than forbidden.** It claimed 50 TypeScript, 14 Python and 16 Lua files on 2026-08-19
# against a real 55, 15 and 22 -- the Lua figure had been wrong for a day and nobody
# noticed, because a number in a table has nothing keeping it true.
#
# **The globs are the definition, not an approximation of one.** TypeScript counts `.mjs`
# because Biome lints it and the row is about what that linter covers.
LANGUAGE_FILES: dict[str, tuple[str, ...]] = {
    "TypeScript": ("*.ts", "*.mjs"),
    "Python": ("*.py",),
    "Lua": ("*.lua",),
    "SQL": ("*.sql",),
    "Svelte": ("*.svelte",),
}

NUMBER_WORDS: dict[str, int] = {
    word: value
    for value, word in enumerate(
        [
            "zero",
            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "ten",
            "eleven",
            "twelve",
            "thirteen",
            "fourteen",
            "fifteen",
            "sixteen",
            "seventeen",
            "eighteen",
            "nineteen",
            "twenty",
        ]
    )
}


def hits_in(text: str) -> list[tuple[int, str, str]]:
    """Return every forbidden count in `text` as (line number, matched text, line)."""
    found: list[tuple[int, str, str]] = []
    for number, line in enumerate(text.splitlines(), start=1):
        if MARKER in line:
            continue
        found.extend(
            (number, match.group(0), line.strip()) for match in COUNT.finditer(line)
        )
    return found


#: How many rule families `ruff.toml` selects, as CLAUDE.md states it. Derivable, so it
#: is verified rather than deleted -- it said 20 against a real 21 on 2026-08-19.
RUFF_CLAIM: re.Pattern[str] = re.compile(r"`ruff`,\s*(\d+)\s+families")


#: Where the Worker declares its routes, and the shape of a declaration.
ROUTE_SOURCES: tuple[str, ...] = ("src/routes/*.ts", "src/index.ts")
ROUTE_DEF: re.Pattern[str] = re.compile(r'\.(?:get|post|put|delete|all)\(\s*"(/[^"]*)"')

#: A path-looking token in prose.
#:
#: **THE TRAILING SLASH ON EACH PREFIX IS LOAD-BEARING, and a version without it cried
#: wolf ten times out of eleven.** Anchoring on `/api` matched seven sentences about the
#: prefix itself; anchoring on `/auth` swallowed Flickr's own `/authorize` in FLICKR.md
#: and `/api/upload` in a spike note. Requiring `/api/v001/` and `/auth/` names only
#: paths this Worker could possibly own. Trailing punctuation is trimmed for `/api,`.
DOC_PATH: re.Pattern[str] = re.compile(
    r"(/(?:api/v001|auth)/[A-Za-z0-9_/:{},*-]*|/health\b)"
)


def expand_braces(candidate: str) -> list[str]:
    """Turn `/a/{b,c}/d` into `/a/b/d` and `/a/c/d`.

    **Documents write route families as one token**, and a checker that read
    `{start,poll}` as a literal segment would report two defects for a correct line.
    """
    match = re.search(r"\{([^{}]*)\}", candidate)
    if match is None:
        return [candidate]
    out: list[str] = []
    for option in match.group(1).split(","):
        replaced = candidate[: match.start()] + option.strip() + candidate[match.end() :]
        out.extend(expand_braces(replaced))
    return out


def path_segments(path: str) -> list[str]:
    """Path segments, with every parameter form collapsed to one placeholder."""
    parts: list[str] = []
    for raw in path.strip("/").split("/"):
        if raw.startswith(":") or (raw.startswith("{") and raw.endswith("}")):
            parts.append("*")
        else:
            parts.append(raw)
    return parts


def matches_route(candidate: str, routes: list[str]) -> bool:
    """Whether `candidate` names a route that exists.

    **A trailing `*` or `/` is PREFIX notation, not a path.** `/api/v001/*` is how every
    document here refers to the authenticated surface, and demanding that it name a
    route would make the check unusable.
    """
    trimmed = candidate.rstrip(",.;:)")
    prefix = trimmed.endswith(("*", "/"))
    want = path_segments(trimmed.rstrip("*").rstrip("/"))
    if not want or want == [""]:
        return True

    for route in routes:
        have = path_segments(route)
        if prefix:
            if len(have) < len(want):
                continue
            have = have[: len(want)]
        elif len(have) != len(want):
            continue
        if all(a == b or "*" in (a, b) for a, b in zip(have, want, strict=True)):
            return True
    return False


def defined_routes() -> list[str]:
    """Every route path the Worker declares."""
    found: list[str] = []
    for pattern in ROUTE_SOURCES:
        result = subprocess.run(
            ["git", "ls-files", pattern],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        for relative in result.stdout.splitlines():
            if not relative.strip():
                continue
            text = (REPO_ROOT / relative.strip()).read_text(encoding="utf-8")
            found.extend(ROUTE_DEF.findall(text))
    return sorted(set(found))


def ruff_families() -> int:
    """How many rule families `ruff.toml` selects."""
    config = tomllib.loads((REPO_ROOT / "ruff.toml").read_text(encoding="utf-8"))
    select = config.get("lint", config).get("select", [])
    return len(select)


def tracked_count(patterns: tuple[str, ...]) -> int:
    """How many git-tracked files match any of `patterns`."""
    result = subprocess.run(
        ["git", "ls-files", *patterns],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return len([line for line in result.stdout.splitlines() if line.strip()])


def language_rows(text: str) -> list[tuple[int, str, int]]:
    """Every language-table row in `text` as (line number, language, stated count).

    **Rows whose count cell is not a plain number are skipped**, which is how the
    `CSS / HTML` row survives saying "1 each". A checker that demanded a number there
    would be asking the table to be less clear than it is.
    """
    rows: list[tuple[int, str, int]] = []
    for number, line in enumerate(text.splitlines(), start=1):
        if not line.startswith("|"):
            continue
        cells = [cell.strip().strip("*").strip() for cell in line.split("|")]
        if len(cells) < 3:
            continue
        language, stated = cells[1], cells[2]
        if language not in LANGUAGE_FILES or not stated.isdigit():
            continue
        rows.append((number, language, int(stated)))
    return rows


def tracked_markdown() -> list[str]:
    """Return every git-tracked markdown path, repository-relative, with / separators."""
    result = subprocess.run(
        ["git", "ls-files", "*.md"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def gate_steps() -> int:
    """Return how many steps `npm run check` runs, read from package.json."""
    raw = (REPO_ROOT / "package.json").read_text(encoding="utf-8")
    check: str = json.loads(raw)["scripts"]["check"]
    return len([step for step in check.split("&&") if step.strip()])


def documented_steps(text: str) -> tuple[int, int] | None:
    """Return (line number, count) for the gate's step count in `text`, or None."""
    for number, line in enumerate(text.splitlines(), start=1):
        match = STEPS.search(line)
        if match is None:
            continue
        token = match.group(1).lower()
        if token.isdigit():
            return (number, int(token))
        if token in NUMBER_WORDS:
            return (number, NUMBER_WORDS[token])
        return (number, -1)
    return None


def self_test() -> bool:
    """Prove both polarities. Returns True when every case behaves."""
    must_fire: list[str] = [
        "The gate runs 305 tests, the traceability gate, and the web build.",
        "It breaks the source in 46 mutations and checks the suite screams.",
        "Deleting the first pass left all 53 checks green.",
        "The matrix holds 61 test blocks today.",
        "There are 25 decisions in this file.",
        "It passed 24 Tests on the first run.",
    ]
    must_not_fire: list[str] = [
        # This one is the defect the first run found. Keep it first.
        "**`workerd` implements HMAC-SHA1.** Verified against RFC 2202 test vectors.",
        f"Nothing failed and 297 tests passed throughout.   <!-- {MARKER}: historical -->",
        "Quote the number the runner prints, never one read from a document.",
        "The ADR-23 Rule 3 import gate reads two committed indexes.",
        "The second mutation, on the surviving filter, drew 5 failures.",
        "**Sixteen steps, in this order.** Typecheck, Biome, the dirty-words check.",
        "This count has now been wrong FOUR times.",
        "The suite is green.",
        "Read `scripts/lrc-sdk-api.json`, 355 members across 38 namespaces.",
    ]

    # **Every one of these false positives was produced by a real earlier version.**
    fake_routes = [
        "/api/v001/photos/:photoId/preflight",
        "/auth/device-link/start",
        "/auth/device-link/poll",
        "/health",
    ]
    route_ok = [
        "/api/v001/*",
        "/api/v001/",
        "/auth/device-link/{start,poll}",
        "/api/v001/photos/{photoId}/preflight",
        "/api/v001/photos/:photoId/preflight",
        "/health",
        "/api/v001/photos/:photoId/preflight,",
    ]
    route_bad = ["/api/v001/device/start", "/api/v001/nope"]
    # Tokens an earlier anchor swallowed. None may even be EXTRACTED as a candidate.
    not_a_path = ["the /api prefix", "Flickr's /authorize leg", "POST /api/upload here"]

    failures: list[str] = [f"MISSED: {case}" for case in must_fire if not hits_in(case)]
    failures.extend(
        f"ROUTE FALSE POSITIVE on {one!r}"
        for case in route_ok
        for one in expand_braces(case)
        if not matches_route(one, fake_routes)
    )
    failures.extend(
        f"ROUTE MISSED: {case!r} matched a route that does not exist"
        for case in route_bad
        if matches_route(case, fake_routes)
    )
    failures.extend(
        f"ROUTE OVER-MATCH: {case!r} is prose, not a path"
        for case in not_a_path
        if DOC_PATH.findall(case)
    )
    for case in must_not_fire:
        found = hits_in(case)
        if found:
            failures.append(f"FALSE POSITIVE on {case!r}: matched {found[0][1]!r}")

    if failures:
        print("Self-test FAILED:")
        for failure in failures:
            print(f"  {failure}")
        return False

    print(
        f"Self-test passed: {len(must_fire)} lines fire, {len(must_not_fire)} stay silent."
    )
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refuse a live count of tests, mutations or checks stated in prose."
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="run only the self-test and exit",
    )
    args = parser.parse_args()

    if not self_test():
        return 1
    if args.self_test:
        return 0

    problems: int = 0
    scanned: int = 0

    for relative in tracked_markdown():
        if relative in SKIP:
            print(f"Skipped {relative} -- {SKIP[relative]}.")
            continue
        path = REPO_ROOT / relative
        text = path.read_text(encoding="utf-8")
        scanned += 1
        for number, matched, line in hits_in(text):
            problems += 1
            print(f"{relative}:{number}: states a live count -- {matched!r}")
            print(f"    {line}")

    expected = gate_steps()
    claude_md = (REPO_ROOT / "CLAUDE.md").read_text(encoding="utf-8")
    documented = documented_steps(claude_md)
    if documented is None:
        problems += 1
        print("CLAUDE.md: no gate step count found. Expected '**N steps, in this order.**'.")
    else:
        line_number, stated = documented
        if stated != expected:
            problems += 1
            print(
                f"CLAUDE.md:{line_number}: says {stated} gate steps, "
                f"package.json runs {expected}."
            )
        else:
            print(f"Gate step count agrees: {expected} steps in package.json and CLAUDE.md.")

    rows = language_rows(claude_md)

    # **EVERY language MUST be found, not merely some.** Checking only that the list is
    # non-empty is the silent-inertness shape this repository keeps paying for: one row
    # reformatted, or a language renamed in the table, and that row simply stops being
    # checked while the run still prints a reassuring line. Card #0033 exists because a
    # probe went inert exactly this way.
    missing = sorted(set(LANGUAGE_FILES) - {language for _, language, _ in rows})
    if missing:
        problems += 1
        print(
            "CLAUDE.md: the language table is missing a checkable row for "
            f"{', '.join(missing)}. The table moved, or its shape changed."
        )

    for line_number, language, stated in rows:
        real = tracked_count(LANGUAGE_FILES[language])
        if stated != real:
            problems += 1
            print(
                f"CLAUDE.md:{line_number}: says {stated} {language} file(s), "
                f"git tracks {real}."
            )
    if rows and problems == 0:
        print(f"Language file counts agree: {len(rows)} row(s) match git ls-files.")

    # **A route path in a document is derivable, so it is VERIFIED.** The README named
    # `POST /api/v001/device/{...}` for a day after that prefix was deleted, in the row
    # describing the protected surface. Card #0114.
    routes = defined_routes()
    if not routes:
        problems += 1
        print("No routes found in src/. The declaration shape changed, or the files moved.")
    checked_paths = 0
    for relative in tracked_markdown():
        if relative in SKIP:
            continue
        for number, line in enumerate(
            (REPO_ROOT / relative).read_text(encoding="utf-8").splitlines(), start=1
        ):
            if MARKER in line:
                continue
            for token in DOC_PATH.findall(line):
                for candidate in expand_braces(token):
                    checked_paths += 1
                    if not matches_route(candidate, routes):
                        problems += 1
                        print(
                            f"{relative}:{number}: names {candidate!r}, "
                            "which no route defines."
                        )
    if routes:
        print(
            f"Documented routes resolve: {checked_paths} path(s) checked "
            f"against {len(routes)} route(s)."
        )

    families = ruff_families()
    claims = [
        (number, int(match.group(1)))
        for number, line in enumerate(claude_md.splitlines(), start=1)
        if (match := RUFF_CLAIM.search(line)) is not None
    ]
    if not claims:
        problems += 1
        print("CLAUDE.md: no `ruff`, N families claim found. The wording changed.")
    for line_number, stated in claims:
        if stated != families:
            problems += 1
            print(
                f"CLAUDE.md:{line_number}: says ruff selects {stated} families, "
                f"ruff.toml selects {families}."
            )
        else:
            print(f"Ruff family count agrees: {families} in ruff.toml and CLAUDE.md.")

    if problems:
        print()
        print(f"Found {problems} stale-count problem(s).")
        print(
            f"A live count belongs in the runner's output, not in prose. "
            f"Mark a historical sentence with '{MARKER}: <reason>' on its line."
        )
        return 1

    print(f"No live counts in prose. Scanned {scanned} tracked markdown files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
